### ISSUE TITLE
docker exec执行的/bin/bash可否改为由ssh客户端提供？

### ISSUE THREAD

**Issue by dotNetDR** [domeos/dockerConnector#1]
英文不才，用中文描述吧

[docker exec -it /bin/bash](https://github.com/domeos/dockerConnector/blob/master/dockerConnector/connector/connector.go#L105)

centos:lstest镜像里面有/bin/bash，顾这个docker exec -it /bin/bash执行没有问题，换作busybox:latest镜像就没那么幸运了，因为里面就只有/bin/sh了，能不能提供一些ssh资料？

或者能实现，将/bin/sh带到docker exec里就最好不过了。
```shell
ssh 64c286ee0391@192.168.20.3 -p 2222 /bin/sh
```

还有后续的 [switch req.Type](https://github.com/domeos/dockerConnector/blob/master/dockerConnector/connector/connector.go#L124-L138) 这样写的作用是？可否有相关参考资料提供？

谢谢~~~

**Comment by dotNetDR** [comment]
当遍历到 req.Type = "exec" 时，req.Payload属性便是/bin/sh了。

**Comment by fridayis** [comment]
谢谢您的建议~ 当前的dockerConnector是一个初步的版本，默认使用/bin/bash进入容器的shell环境，对不存在bash指令的容器登录会有问题。如果指定shell指令并带入ssh命令，需要修改DomeOS进入容器控制台部分的交互方式，我们会考虑在下一版本中添加这个功能。
程序中用到的ssh服务端代码文档：https://godoc.org/golang.org/x/crypto/ssh，可参考。
